spring.application.name=pix

# Configurações gerais do banco apontando para as Variáveis de Ambiente
spring.datasource.url=jdbc:mysql://localhost:3306/pix?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
